spring:
  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/hometown

    username: admin

    password: 123456


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名
    map-underscore-to-camel-case: true
  #??mapper文件存放路径
  mapper-locations: classpath:cyber/hometown2/mapper/*.xml
